config/routes.rb
Rails.application.routes.draw do
  resources :chats
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat.rb
class Chat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :set_chat, only: %i[ show edit update destroy ]

  # GET /chats or /chats.json
  def index
    @chats = Chat.all
  end

  # GET /chats/1 or /chats/1.json
  def show
  end

  # GET /chats/new
  def new
    @chat = Chat.new
  end

  # GET /chats/1/edit
  def edit
  end

  # POST /chats or /chats.json
  def create
    @chat = Chat.new(chat_params)

    respond_to do |format|
      if @chat.save
        format.html { redirect_to chat_url(@chat), notice: "Chat was successfully created." }
        format.json { render :show, status: :created, location: @chat }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chats/1 or /chats/1.json
  def update
    respond_to do |format|
      if @chat.update(chat_params)
        format.html { redirect_to chat_url(@chat), notice: "Chat was successfully updated." }
        format.json { render :show, status: :ok, location: @chat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chats/1 or /chats/1.json
  def destroy
    @chat.destroy

    respond_to do |format|
      format.html { redirect_to chats_url, notice: "Chat was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chat
      @chat = Chat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def chat_params
      params.require(:chat).permit(:name, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/views/chats/_chat.html.erb
<div id="<%= dom_id chat %>">
  <p>
    <strong>Name:</strong>
    <%= chat.name %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= chat.content %>
  </p>

</div>

app/views/chats/_form.html.erb
<%= form_with(model: chat) do |form| %>
  <% if chat.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(chat.errors.count, "error") %> prohibited this chat from being saved:</h2>

      <ul>
        <% chat.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_field :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/chats/edit.html.erb
<h1>Editing chat</h1>

<%= render "form", chat: @chat %>

<br>

<div>
  <%= link_to "Show this chat", @chat %> |
  <%= link_to "Back to chats", chats_path %>
</div>

app/views/chats/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Chats</h1>

<div id="chats">
  <% @chats.each do |chat| %>
    <%= render chat %>
    <p>
      <%= link_to "Show this chat", chat %>
    </p>
  <% end %>
</div>

<%= link_to "New chat", new_chat_path %>

app/views/chats/new.html.erb
<h1>New chat</h1>

<%= render "form", chat: @chat %>

<br>

<div>
  <%= link_to "Back to chats", chats_path %>
</div>

app/views/chats/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @chat %>

<div>
  <%= link_to "Edit this chat", edit_chat_path(@chat) %> |
  <%= link_to "Back to chats", chats_path %>

  <%= button_to "Destroy this chat", @chat, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotwireChatsSqlite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>